# This is a basic workflow to help you get started with Actions

name: Build and Deploy Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
    # Trigger when either files in the docs folder, the requirements.txt file or the mkdocs.yml file are edited and commited.
    paths:
      - 'docs/**'
      - 'requirements.txt'
      - 'mkdocs.yml'
  pull_request:
    branches:  ['main']
    # Trigger when either files in the docs folder, the requirements.txt file or the mkdocs.yml file are edited and commited.
    paths:
      - 'docs/**'
      - 'requirements.txt'
      - 'mkdocs.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# These permissions are required for it to work
permissions:
  contents: read
  pages: write
  id-token: write

# Makes sure only one workflow runs at a time.
concurrency:
  group: 'pages'
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This environment is required!
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python_version: '3.x' # Uses latest 3.x version.

      # Alternatively: pip install mkdocs
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 
      - name: Build Docs
        run: mkdocs build

      # 
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'site/' # MkDocs builds to site/ by default

      #
      - name: Deploy to GitHub Pages
        id: deployment # This is required for environment
        uses: actions/deploy-pages@v2
